# Generated by Django 5.2.12 on 2026-04-02 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='immagini_aste/')),
                ('data_scadenza', models.DateTimeField()),
                ('attiva', models.BooleanField(default=True)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aste_create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_offerta', models.DateField(auto_now_add=True)),
                ('asta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte', to='gestione_aste.asta')),
                ('offerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerte_create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
