# Generated by Django on 2026-04-20
from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Categoria = apps.get_model('gestione_aste', 'Categoria')
    categories = [
        {'nome': 'Elettronica', 'descrizione': 'Gadget, Computer, Smartphone e altro.'},
        {'nome': 'Arredamento', 'descrizione': 'Mobili, Complementi e Oggettistica.'},
        {'nome': 'Arte', 'descrizione': 'Dipinti, Sculture e Opere varie.'},
        {'nome': 'Gioielli', 'descrizione': 'Orologi, Oro, Argento e Pietre Preziose.'},
        {'nome': 'Veicoli', 'descrizione': 'Auto, Moto e Mezzi di trasporto.'},
        {'nome': 'Collezionismo', 'descrizione': 'Monete, Francobolli e oggetti rari.'},
        {'nome': 'Altro', 'descrizione': 'Tutto ciò che non rientra nelle altre categorie.'},
    ]
    for cat_data in categories:
        Categoria.objects.get_or_create(nome=cat_data['nome'], defaults={'descrizione': cat_data['descrizione']})

def remove_initial_categories(apps, schema_editor):
    Categoria = apps.get_model('gestione_aste', 'Categoria')
    category_names = ['Elettronica', 'Arredamento', 'Arte', 'Gioielli', 'Veicoli', 'Collezionismo', 'Altro']
    Categoria.objects.filter(nome__in=category_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, remove_initial_categories),
    ]
