# Generated by Django 5.2.12 on 2026-04-03 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asta',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asta',
            name='prezzo_iniziale',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
