# Generated by Django 5.2.13 on 2026-04-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativoIntrusione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indirizzo_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('data_tentativo', models.DateTimeField(auto_now_add=True)),
                ('username_tentato', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
