# Generated by Django 5.2.12 on 2026-04-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0002_asta_data_creazione_asta_prezzo_iniziale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asta',
            old_name='imagine',
            new_name='immagine',
        ),
    ]
