# Generated by Django 5.2.12 on 2026-04-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0003_rename_imagine_asta_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerta',
            name='data_offerta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
