# Generated by Django 5.2.12 on 2026-04-04 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0005_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='asta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestione_aste.categoria'),
        ),
    ]
