# Generated by Django 5.2.12 on 2026-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0007_asta_prezzo_corrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asta',
            name='prezzo_corrente',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, default=0.0, max_digits=10), max_digits=10),
        ),
    ]
