# Generated by Django 5.2.12 on 2026-04-12 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0008_alter_asta_prezzo_corrente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asta',
            name='preferiti',
            field=models.ManyToManyField(blank=True, related_name='aste_preferite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asta',
            name='prezzo_corrente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
