# Generated by Django 5.2.12 on 2026-04-13 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0010_recensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='asta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recensione', to='gestione_aste.asta'),
        ),
    ]
