# Generated by Django 5.2.13 on 2026-04-13 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0011_recensione_asta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenuto', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('letto', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_ricevuti', to=settings.AUTH_USER_MODEL)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaggi_inviati', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_invio'],
            },
        ),
    ]
