# Generated by Django 5.2.13 on 2026-04-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_aste', '0012_messaggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaggio',
            name='asta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaggi', to='gestione_aste.asta'),
        ),
    ]
